import React from "react";
import type { Metadata } from "next";
import "@/styles/globals.css";
// import { useFluidTypography } from "@/hooks/useFluidTypography";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const rootFontSize = useFluidTypography();
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
