import React from "react";
import type { Metadata } from "next";
import "@/styles/globals.css";
import { languages } from "@/lib/i18n/setting";

type Lang = {
  lng: string;
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return languages.map((lng) => ({
    lng,
  }));
}
export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Lang;
}>) {
  return (
    <html lang={params.lng} dir={params.lng}>
      <body>{children}</body>
    </html>
  );
}
